
import { Category, Dictionary, LanguageCode, Prompt } from './types';

export const DEFAULT_CATEGORIES: Category[] = [
  { id: '1', name: 'Art & Design', color: 'bg-pink-500', icon: 'Palette' },
  { id: '2', name: 'Coding', color: 'bg-blue-500', icon: 'Code' },
  { id: '3', name: 'Writing', color: 'bg-emerald-500', icon: 'PenTool' },
  { id: '4', name: 'Photography', color: 'bg-purple-500', icon: 'Camera' },
];

export const DEFAULT_PROMPTS: Prompt[] = [
  // Art & Design
  {
    id: 'def-1',
    title: 'Cyberpunk Street',
    description: 'Neon-lit futuristic city environment',
    positive: 'Neon-lit cyberpunk street, rain-slicked pavement, towering skyscrapers with holographic ads, cinematic lighting, highly detailed, 8k, unreal engine 5 render.',
    negative: 'blurry, low quality, distorted, watermark',
    note: 'Best used with SDXL 1.0, aspect ratio 16:9',
    categoryIds: ['1'],
    createdAt: Date.now(),
    updatedAt: Date.now()
  },
  {
    id: 'def-2',
    title: 'Fantasy Landscape',
    description: 'Dreamlike floating islands',
    positive: 'Ethereal floating islands, waterfalls cascading into clouds, vibrant fantasy flora, dreamlike atmosphere, digital painting, artstation.',
    negative: 'dark, gloomy, pixelated',
    note: 'Try increasing guidance scale for more vibrancy.',
    categoryIds: ['1'],
    createdAt: Date.now(),
    updatedAt: Date.now()
  },
  {
    id: 'def-3',
    title: 'Warrior Portrait',
    description: 'Detailed character design',
    positive: 'Close-up portrait of a warrior princess with intricate golden armor, fierce expression, dramatic lighting, photorealistic, sharp focus.',
    negative: 'helmet, ugly, deformed eyes',
    note: 'Reference style: Greg Rutkowski',
    categoryIds: ['1'],
    createdAt: Date.now(),
    updatedAt: Date.now()
  },
  {
    id: 'def-4',
    title: 'Abstract Oil Painting',
    description: 'Expressionist style art',
    positive: 'Abstract expressionist oil painting, chaotic brushstrokes, vibrant colors, emotional, textured, thick paint impasto.',
    negative: 'smooth, digital, vector',
    note: 'Use a lower step count for rougher texture.',
    categoryIds: ['1'],
    createdAt: Date.now(),
    updatedAt: Date.now()
  },
  {
    id: 'def-5',
    title: 'Isometric Gamer Room',
    description: '3D cute room render',
    positive: 'Cute isometric gamer room, pastel colors, cozy atmosphere, low poly 3d render, soft lighting, blender 3d.',
    negative: 'noisy, realistic, dark',
    note: 'Great for app icons or game assets.',
    categoryIds: ['1'],
    createdAt: Date.now(),
    updatedAt: Date.now()
  },
  // Coding
  {
    id: 'def-6',
    title: 'React Button Component',
    description: 'Reusable UI component',
    positive: 'Create a reusable React button component with Tailwind CSS variants for primary, secondary, and ghost styles. Include TypeScript interfaces.',
    note: 'Remember to check for accessibility props.',
    categoryIds: ['2'],
    createdAt: Date.now(),
    updatedAt: Date.now()
  },
  {
    id: 'def-7',
    title: 'Python Web Scraper',
    description: 'BeautifulSoup script',
    positive: 'Write a Python script to scrape product prices from a website using BeautifulSoup and save them to a CSV file. Handle pagination.',
    note: 'Respect robots.txt when testing.',
    categoryIds: ['2'],
    createdAt: Date.now(),
    updatedAt: Date.now()
  },
  {
    id: 'def-8',
    title: 'Complex SQL Query',
    description: 'Customer analytics',
    positive: 'Write a complex SQL query to find the top 5 spending customers in the last month, joining users and orders tables, grouped by user ID.',
    note: 'Ensure indexes are used on foreign keys.',
    categoryIds: ['2'],
    createdAt: Date.now(),
    updatedAt: Date.now()
  },
  {
    id: 'def-9',
    title: 'Regex for Email',
    description: 'Validation pattern',
    positive: 'Generate a robust regular expression to validate email addresses that supports modern TLDs and prevents common injection attacks.',
    note: 'Test with edge cases like subdomain.co.uk',
    categoryIds: ['2'],
    createdAt: Date.now(),
    updatedAt: Date.now()
  },
  {
    id: 'def-10',
    title: 'Node.js Auth Endpoint',
    description: 'Express API route',
    positive: 'Design a RESTful API endpoint in Node.js Express for user registration with input validation (zod) and password hashing (bcrypt).',
    note: 'Use salt rounds >= 10.',
    categoryIds: ['2'],
    createdAt: Date.now(),
    updatedAt: Date.now()
  },
  // Writing
  {
    id: 'def-11',
    title: 'Blog Intro: Tech',
    description: 'Opening for a tech article',
    positive: 'Write a catchy introduction for a blog post about the benefits of meditation for software developers. Hook the reader immediately.',
    note: 'Tone: Professional yet relatable.',
    categoryIds: ['3'],
    createdAt: Date.now(),
    updatedAt: Date.now()
  },
  {
    id: 'def-12',
    title: 'Sci-Fi Story Opener',
    description: 'Creative writing prompt',
    positive: 'Write the opening paragraph of a sci-fi novel where the protagonist discovers a message from their future self hidden in a legacy code base.',
    note: 'Genre: Cyberpunk / Mystery',
    categoryIds: ['3'],
    createdAt: Date.now(),
    updatedAt: Date.now()
  },
  {
    id: 'def-13',
    title: 'Client Apology Email',
    description: 'Professional communication',
    positive: 'Draft a professional email to a client explaining a delay in the project timeline due to unforeseen technical challenges. Propose a new deadline.',
    note: 'Keep it concise and solution-oriented.',
    categoryIds: ['3'],
    createdAt: Date.now(),
    updatedAt: Date.now()
  },
  {
    id: 'def-14',
    title: 'Product Description',
    description: 'Marketing copy',
    positive: 'Write a persuasive product description for a noise-cancelling headphone with 30-hour battery life, focusing on comfort and audio fidelity.',
    note: 'Target audience: Audiophiles and travelers.',
    categoryIds: ['3'],
    createdAt: Date.now(),
    updatedAt: Date.now()
  },
  {
    id: 'def-15',
    title: 'Developer Haiku',
    description: 'Short poem',
    positive: 'Write a haiku about the feeling of compiling code successfully after hours of debugging errors.',
    note: 'Just for fun!',
    categoryIds: ['3'],
    createdAt: Date.now(),
    updatedAt: Date.now()
  },
  // Photography
  {
    id: 'def-16',
    title: 'Portrait Setup',
    description: 'Elderly portrait guide',
    positive: 'Portrait of an elderly man with a weathered face, natural light, shallow depth of field, 85mm lens, black and white, rembrandt lighting.',
    negative: 'flash glare, oversaturated',
    note: 'Camera: Sony A7R IV',
    categoryIds: ['4'],
    createdAt: Date.now(),
    updatedAt: Date.now()
  },
  {
    id: 'def-17',
    title: 'Landscape Sunrise',
    description: 'Nature photography prompt',
    positive: 'Wide angle shot of a mountain range at sunrise, golden hour, mist in the valleys, sharp focus, f/16, high dynamic range.',
    note: 'Tripod essential for this shot.',
    categoryIds: ['4'],
    createdAt: Date.now(),
    updatedAt: Date.now()
  },
  {
    id: 'def-18',
    title: 'Macro Spider Web',
    description: 'Close-up detail',
    positive: 'Macro photography of a dew drop on a spider web, refraction of the background, crisp details, bokeh, morning light.',
    note: 'Lens: 100mm Macro',
    categoryIds: ['4'],
    createdAt: Date.now(),
    updatedAt: Date.now()
  },
  {
    id: 'def-19',
    title: 'Tokyo Street',
    description: 'Urban photography',
    positive: 'Candid street photography in Tokyo, busy crosswalk at night, motion blur of cars, sharp focus on a pedestrian, cyberpunk vibes.',
    note: 'Shutter speed: 1/60s',
    categoryIds: ['4'],
    createdAt: Date.now(),
    updatedAt: Date.now()
  },
  {
    id: 'def-20',
    title: 'Gourmet Burger',
    description: 'Food photography',
    positive: 'Top-down shot of a gourmet burger on a wooden board, rustic styling, soft natural lighting, appetizing, commercial food photography.',
    note: 'Use a reflector to fill shadows.',
    categoryIds: ['4'],
    createdAt: Date.now(),
    updatedAt: Date.now()
  }
];

export const TRANSLATIONS: Record<LanguageCode, Dictionary> = {
  en: {
    appTitle: 'PromptsGo',
    searchPlaceholder: 'Search prompts...',
    newPrompt: 'New Prompt',
    categories: 'Categories',
    allPrompts: 'All Prompts',
    globalPrompts: 'Global Prompts',
    myLibrary: 'My Library',
    uncategorized: 'Uncategorized',
    edit: 'Edit',
    delete: 'Delete',
    copy: 'Copy',
    copied: 'Copied!',
    save: 'Save',
    cancel: 'Cancel',
    title: 'Title',
    description: 'Description',
    positivePrompt: 'Positive Prompt',
    negativePrompt: 'Negative Prompt',
    note: 'Note',
    notePlaceholder: 'Add private notes, model settings, or tips...',
    selectCategories: 'Select Categories',
    noPrompts: 'No prompts found. Create one to get started!',
    refineWithAI: 'Refine with AI',
    refining: 'Refining...',
    confirmDelete: 'Are you sure you want to delete this?',
    manageCategories: 'Manage',
    addCategory: 'Add Category',
    settings: 'Settings',
    language: 'Language',
    theme: 'Theme',
    themeLight: 'Light',
    themeDark: 'Dark',
    themeBinder: 'Binder',
    themeJournal: 'Journal',
    themeGlass: 'Glass',
    categoryName: 'Category Name',
    categoryColor: 'Color',
    categoryIcon: 'Icon',
    create: 'Create',
    login: 'Login',
    logout: 'Logout',
    share: 'Share',
    shareToGlobal: 'Share to Global Prompts',
    shareDescription: 'Share your prompt with the community. You can refine it before publishing.',
    anonymous: 'Share Anonymously',
    tags: 'Tags',
    tagsPlaceholder: 'e.g. landscape, sci-fi, realistic (comma separated)',
    uploadImage: 'Upload Reference Image',
    publish: 'Publish to Global',
    comments: 'Comments',
    writeComment: 'Write a comment...',
    noComments: 'No comments yet. Be the first!',
    loginToComment: 'Log in to rate and comment',
    rating: 'Rating',
    image: 'Image',
  },
  'zh-TW': {
    appTitle: 'PromptsGo',
    searchPlaceholder: '搜尋提示詞...',
    newPrompt: '新增提示詞',
    categories: '分類',
    allPrompts: '所有提示詞',
    globalPrompts: '全球提示詞',
    myLibrary: '我的收藏',
    uncategorized: '未分類',
    edit: '編輯',
    delete: '刪除',
    copy: '複製',
    copied: '已複製！',
    save: '儲存',
    cancel: '取消',
    title: '標題',
    description: '描述',
    positivePrompt: '正向提示詞',
    negativePrompt: '反向提示詞',
    note: '筆記',
    notePlaceholder: '新增私人筆記、模型設定或技巧...',
    selectCategories: '選擇分類',
    noPrompts: '找不到提示詞。建立一個新的吧！',
    refineWithAI: 'AI 優化',
    refining: '優化中...',
    confirmDelete: '確定要刪除嗎？',
    manageCategories: '管理',
    addCategory: '新增分類',
    settings: '設定',
    language: '語言',
    theme: '主題',
    themeLight: '明亮',
    themeDark: '深色',
    themeBinder: '皮革手帳',
    themeJournal: '復古日記',
    themeGlass: '玻璃',
    categoryName: '分類名稱',
    categoryColor: '顏色',
    categoryIcon: '圖示',
    create: '建立',
    login: '登入',
    logout: '登出',
    share: '分享',
    shareToGlobal: '分享至全球提示詞',
    shareDescription: '將您的提示詞分享給社群。發布前您可以再次編輯。',
    anonymous: '匿名分享',
    tags: '標籤',
    tagsPlaceholder: '例如：風景, 科幻, 寫實 (以逗號分隔)',
    uploadImage: '上傳參考圖片',
    publish: '發布至全球',
    comments: '評論',
    writeComment: '寫下評論...',
    noComments: '尚未有評論。搶先頭香！',
    loginToComment: '登入以評分和評論',
    rating: '評分',
    image: '圖片',
  },
  ja: {
    appTitle: 'PromptsGo',
    searchPlaceholder: 'プロンプトを検索...',
    newPrompt: '新規プロンプト',
    categories: 'カテゴリー',
    allPrompts: 'すべてのプロンプト',
    globalPrompts: 'グローバル',
    myLibrary: 'ライブラリ',
    uncategorized: '未分類',
    edit: '編集',
    delete: '削除',
    copy: 'コピー',
    copied: 'コピーしました！',
    save: '保存',
    cancel: 'キャンセル',
    title: 'タイトル',
    description: '説明',
    positivePrompt: 'ポジティブ',
    negativePrompt: 'ネガティブ',
    note: 'メモ',
    notePlaceholder: '個人的なメモ、モデル設定、ヒントを追加...',
    selectCategories: 'カテゴリーを選択',
    noPrompts: 'プロンプトが見つかりません。作成しましょう！',
    refineWithAI: 'AIで改善',
    refining: '改善中...',
    confirmDelete: '本当に削除しますか？',
    manageCategories: '管理',
    addCategory: 'カテゴリー追加',
    settings: '設定',
    language: '言語',
    theme: 'テーマ',
    themeLight: 'ライト',
    themeDark: 'ダーク',
    themeBinder: 'バインダー',
    themeJournal: 'ジャーナル',
    themeGlass: 'グラス',
    categoryName: 'カテゴリー名',
    categoryColor: '色',
    categoryIcon: 'アイコン',
    create: '作成',
    login: 'ログイン',
    logout: 'ログアウト',
    share: '共有',
    shareToGlobal: 'グローバルに共有',
    shareDescription: 'コミュニティと共有します。公開前に編集できます。',
    anonymous: '匿名で共有',
    tags: 'タグ',
    tagsPlaceholder: '例: 風景, SF, リアル (カンマ区切り)',
    uploadImage: '参考画像をアップロード',
    publish: 'グローバルに公開',
    comments: 'コメント',
    writeComment: 'コメントを書く...',
    noComments: 'コメントはまだありません。',
    loginToComment: 'ログインして評価・コメント',
    rating: '評価',
    image: '画像',
  },
};
