
import { Category, Dictionary, LanguageCode, Prompt } from './types';

export const DEFAULT_CATEGORIES: Category[] = [
  { id: '1', name: 'Art & Design', color: 'bg-pink-500', icon: 'Palette' },
  { id: '2', name: 'Coding', color: 'bg-blue-500', icon: 'Code' },
  { id: '3', name: 'Writing', color: 'bg-emerald-500', icon: 'PenTool' },
  { id: '4', name: 'Photography', color: 'bg-purple-500', icon: 'Camera' },
];

export const DEFAULT_PROMPTS: Prompt[] = [
  // Art & Design
  {
    id: 'def-1',
    title: 'Cyberpunk Street (sample)',
    description: 'Neon-lit futuristic city environment',
    positive: 'Neon-lit cyberpunk street, rain-slicked pavement, towering skyscrapers with holographic ads, cinematic lighting, highly detailed, 8k, unreal engine 5 render.',
    negative: 'blurry, low quality, distorted, watermark',
    note: 'Best used with SDXL 1.0, aspect ratio 16:9',
    categoryIds: ['1'],
    createdAt: Date.now(),
    updatedAt: Date.now()
  },
  {
    id: 'def-2',
    title: 'Fantasy Landscape (sample)',
    description: 'Dreamlike floating islands',
    positive: 'Ethereal floating islands, waterfalls cascading into clouds, vibrant fantasy flora, dreamlike atmosphere, digital painting, artstation.',
    negative: 'dark, gloomy, pixelated',
    note: 'Try increasing guidance scale for more vibrancy.',
    categoryIds: ['1'],
    createdAt: Date.now(),
    updatedAt: Date.now()
  },
  {
    id: 'def-3',
    title: 'Warrior Portrait (sample)',
    description: 'Detailed character design',
    positive: 'Close-up portrait of a warrior princess with intricate golden armor, fierce expression, dramatic lighting, photorealistic, sharp focus.',
    negative: 'helmet, ugly, deformed eyes',
    note: 'Reference style: Greg Rutkowski',
    categoryIds: ['1'],
    createdAt: Date.now(),
    updatedAt: Date.now()
  },
  {
    id: 'def-4',
    title: 'Abstract Oil Painting (sample)',
    description: 'Expressionist style art',
    positive: 'Abstract expressionist oil painting, chaotic brushstrokes, vibrant colors, emotional, textured, thick paint impasto.',
    negative: 'smooth, digital, vector',
    note: 'Use a lower step count for rougher texture.',
    categoryIds: ['1'],
    createdAt: Date.now(),
    updatedAt: Date.now()
  },
  {
    id: 'def-5',
    title: 'Isometric Gamer Room (sample)',
    description: '3D cute room render',
    positive: 'Cute isometric gamer room, pastel colors, cozy atmosphere, low poly 3d render, soft lighting, blender 3d.',
    negative: 'noisy, realistic, dark',
    note: 'Great for app icons or game assets.',
    categoryIds: ['1'],
    createdAt: Date.now(),
    updatedAt: Date.now()
  },
  // Coding
  {
    id: 'def-6',
    title: 'React Button Component (sample)',
    description: 'Reusable UI component',
    positive: 'Create a reusable React button component with Tailwind CSS variants for primary, secondary, and ghost styles. Include TypeScript interfaces.',
    note: 'Remember to check for accessibility props.',
    categoryIds: ['2'],
    createdAt: Date.now(),
    updatedAt: Date.now()
  },
  {
    id: 'def-7',
    title: 'Python Web Scraper (sample)',
    description: 'BeautifulSoup script',
    positive: 'Write a Python script to scrape product prices from a website using BeautifulSoup and save them to a CSV file. Handle pagination.',
    note: 'Respect robots.txt when testing.',
    categoryIds: ['2'],
    createdAt: Date.now(),
    updatedAt: Date.now()
  },
  {
    id: 'def-8',
    title: 'Complex SQL Query (sample)',
    description: 'Customer analytics',
    positive: 'Write a complex SQL query to find the top 5 spending customers in the last month, joining users and orders tables, grouped by user ID.',
    note: 'Ensure indexes are used on foreign keys.',
    categoryIds: ['2'],
    createdAt: Date.now(),
    updatedAt: Date.now()
  },
  {
    id: 'def-9',
    title: 'Regex for Email (sample)',
    description: 'Validation pattern',
    positive: 'Generate a robust regular expression to validate email addresses that supports modern TLDs and prevents common injection attacks.',
    note: 'Test with edge cases like subdomain.co.uk',
    categoryIds: ['2'],
    createdAt: Date.now(),
    updatedAt: Date.now()
  },
  {
    id: 'def-10',
    title: 'Node.js Auth Endpoint (sample)',
    description: 'Express API route',
    positive: 'Design a RESTful API endpoint in Node.js Express for user registration with input validation (zod) and password hashing (bcrypt).',
    note: 'Use salt rounds >= 10.',
    categoryIds: ['2'],
    createdAt: Date.now(),
    updatedAt: Date.now()
  },
  // Writing
  {
    id: 'def-11',
    title: 'Blog Intro: Tech (sample)',
    description: 'Opening for a tech article',
    positive: 'Write a catchy introduction for a blog post about the benefits of meditation for software developers. Hook the reader immediately.',
    note: 'Tone: Professional yet relatable.',
    categoryIds: ['3'],
    createdAt: Date.now(),
    updatedAt: Date.now()
  },
  {
    id: 'def-12',
    title: 'Sci-Fi Story Opener (sample)',
    description: 'Creative writing prompt',
    positive: 'Write the opening paragraph of a sci-fi novel where the protagonist discovers a message from their future self hidden in a legacy code base.',
    note: 'Genre: Cyberpunk / Mystery',
    categoryIds: ['3'],
    createdAt: Date.now(),
    updatedAt: Date.now()
  },
  {
    id: 'def-13',
    title: 'Client Apology Email (sample)',
    description: 'Professional communication',
    positive: 'Draft a professional email to a client explaining a delay in the project timeline due to unforeseen technical challenges. Propose a new deadline.',
    note: 'Keep it concise and solution-oriented.',
    categoryIds: ['3'],
    createdAt: Date.now(),
    updatedAt: Date.now()
  },
  {
    id: 'def-14',
    title: 'Product Description (sample)',
    description: 'Marketing copy',
    positive: 'Write a persuasive product description for a noise-cancelling headphone with 30-hour battery life, focusing on comfort and audio fidelity.',
    note: 'Target audience: Audiophiles and travelers.',
    categoryIds: ['3'],
    createdAt: Date.now(),
    updatedAt: Date.now()
  },
  {
    id: 'def-15',
    title: 'Developer Haiku (sample)',
    description: 'Short poem',
    positive: 'Write a haiku about the feeling of compiling code successfully after hours of debugging errors.',
    note: 'Just for fun!',
    categoryIds: ['3'],
    createdAt: Date.now(),
    updatedAt: Date.now()
  },
  // Photography
  {
    id: 'def-16',
    title: 'Portrait Setup (sample)',
    description: 'Elderly portrait guide',
    positive: 'Portrait of an elderly man with a weathered face, natural light, shallow depth of field, 85mm lens, black and white, rembrandt lighting.',
    negative: 'flash glare, oversaturated',
    note: 'Camera: Sony A7R IV',
    categoryIds: ['4'],
    createdAt: Date.now(),
    updatedAt: Date.now()
  },
  {
    id: 'def-17',
    title: 'Landscape Sunrise (sample)',
    description: 'Nature photography prompt',
    positive: 'Wide angle shot of a mountain range at sunrise, golden hour, mist in the valleys, sharp focus, f/16, high dynamic range.',
    note: 'Tripod essential for this shot.',
    categoryIds: ['4'],
    createdAt: Date.now(),
    updatedAt: Date.now()
  },
  {
    id: 'def-18',
    title: 'Macro Spider Web (sample)',
    description: 'Close-up detail',
    positive: 'Macro photography of a dew drop on a spider web, refraction of the background, crisp details, bokeh, morning light.',
    note: 'Lens: 100mm Macro',
    categoryIds: ['4'],
    createdAt: Date.now(),
    updatedAt: Date.now()
  },
  {
    id: 'def-19',
    title: 'Tokyo Street (sample)',
    description: 'Urban photography',
    positive: 'Candid street photography in Tokyo, busy crosswalk at night, motion blur of cars, sharp focus on a pedestrian, cyberpunk vibes.',
    note: 'Shutter speed: 1/60s',
    categoryIds: ['4'],
    createdAt: Date.now(),
    updatedAt: Date.now()
  },
  {
    id: 'def-20',
    title: 'Gourmet Burger (sample)',
    description: 'Food photography',
    positive: 'Top-down shot of a gourmet burger on a wooden board, rustic styling, soft natural lighting, appetizing, commercial food photography.',
    note: 'Use a reflector to fill shadows.',
    categoryIds: ['4'],
    createdAt: Date.now(),
    updatedAt: Date.now()
  }
];

export const TRANSLATIONS: Record<LanguageCode, Dictionary> = {
  en: {
    appTitle: 'PromptsGo',
    searchPlaceholder: 'Search prompts...',
    newPrompt: 'New Prompt',
    categories: 'Categories',
    allPrompts: 'All Prompts',
    globalPrompts: 'Global Prompts',
    myLibrary: 'My Library',
    localPrompts: 'Local Prompts',
    uncategorized: 'Uncategorized',
    edit: 'Edit',
    delete: 'Delete',
    copy: 'Copy',
    copied: 'Copied!',
    save: 'Save',
    cancel: 'Cancel',
    title: 'Title',
    description: 'Description',
    positivePrompt: 'Positive Prompt',
    negativePrompt: 'Negative Prompt',
    note: 'Note',
    notePlaceholder: 'Add private notes, model settings, or tips...',
    selectCategories: 'Select Categories',
    noPrompts: 'No prompts found. Create one to get started!',
    refineWithAI: 'Refine with AI',
    refining: 'Refining...',
    confirmDelete: 'Are you sure you want to delete this?',
    manageCategories: 'Manage',
    addCategory: 'Add Category',
    settings: 'Settings',
    language: 'Language',
    theme: 'Theme',
    themeLight: 'Light',
    themeDark: 'Dark',
    themeBinder: 'Binder',
    themeJournal: 'Journal',
    themeGlass: 'Glass',
    themeRoyal: 'Royal',
    themeGreenble: 'Greenble',
    categoryName: 'Category Name',
    categoryColor: 'Color',
    categoryIcon: 'Icon',
    create: 'Create',
    login: 'Login',
    logout: 'Logout',
    share: 'Share',
    shareToGlobal: 'Share to Global Prompts',
    shareDescription: 'Share your prompt with the community. You can refine it before publishing.',
    anonymous: 'Share Anonymously',
    tags: 'Tags',
    tagsPlaceholder: 'e.g. landscape, sci-fi, realistic (comma separated)',
    uploadImage: 'Upload Reference Image',
    publish: 'Publish to Global',
    comments: 'Comments',
    writeComment: 'Write a comment...',
    noComments: 'No comments yet. Be the first!',
    loginToComment: 'Log in to rate and comment',
    rating: 'Rating',
    image: 'Image',
    source: 'Source',
    originalSourceUrl: 'Original Source URL',
    termsOfService: 'Terms of Service',
    privacyPolicy: 'Privacy Policy',
    webViewWarningTitle: 'Open in Browser',
    webViewWarningMessage: 'You are using {app}. For the best experience and to use Google login, please open this website in your browser.',
    webViewWarningMessageGeneric: 'You are using an in-app browser. For the best experience and to use Google login, please open this website in your browser.',
    webViewWarningInstructions: 'Copy the URL above and paste it into Safari, Chrome, or your preferred browser.',
    webViewWarningClose: 'Got it',
    tourNext: 'Next',
    tourStart: 'Start',
    tourStep1Title: 'Local Library',
    tourStep1Content: 'This is where your personal prompts are saved. You can access them anytime, even offline!',
    tourStep2Title: 'Create New',
    tourStep2Content: 'Click here to create a new prompt. AI assistance is built-in to help you refine it.',
    tourStep3Title: 'Categories',
    tourStep3Content: 'Manage your categories here. Customize colors and icons to organize your prompts your way.',
    tourStep4Title: 'Share to Global',
    tourStep4Content: 'Share your best prompts with the community! Click the share icon on any card to publish.',
    tourStep5Title: 'Level Up with Sharing!',
    tourStep5Content: 'Share 5 prompts to unlock your Creator Badge! Keep sharing to earn Silver, Star, and Gold badges.',
    tourComplete: 'Complete Tour',
    selectAll: 'Select All',
    deselectAll: 'Deselect All',
    deleteSelected: 'Delete Selected',

    changeAvatar: 'Change avatar',
    chooseAvatarTitle: 'Choose Avatar',
    levelLabel: 'Level',
    select: 'Select',
    locked: 'Locked',
    upload: 'Upload',
    uploading: 'Uploading...',
    avatarUploadHint: 'Star Creator and above can upload a custom avatar.',
    avatarUploadNotUnlocked: 'Level not unlocked for custom upload yet.',
    avatarUploadNotConfigured: 'Cloudinary is not configured.',
    avatarUploadFailed: 'Upload failed.',

    upgradeGuide: 'Upgrade Guide',
    upgradeGuideTitle: 'Upgrade Guide',
  },
  'zh-TW': {
    appTitle: 'PromptsGo',
    searchPlaceholder: '搜尋提示詞...',
    newPrompt: '新增提示詞',
    categories: '分類',
    allPrompts: '所有提示詞',
    globalPrompts: '全球提示詞',
    myLibrary: '我的收藏',
    localPrompts: '本地提示詞',
    uncategorized: '未分類',
    edit: '編輯',
    delete: '刪除',
    copy: '複製',
    copied: '已複製！',
    save: '儲存',
    cancel: '取消',
    title: '標題',
    description: '描述',
    positivePrompt: '正向提示詞',
    negativePrompt: '反向提示詞',
    note: '筆記',
    notePlaceholder: '新增私人筆記、模型設定或技巧...',
    selectCategories: '選擇分類',
    noPrompts: '找不到提示詞。建立一個新的吧！',
    refineWithAI: 'AI 優化',
    refining: '優化中...',
    confirmDelete: '確定要刪除嗎？',
    manageCategories: '管理',
    addCategory: '新增分類',
    settings: '設定',
    language: '語言',
    theme: '主題',
    themeLight: '明亮',
    themeDark: '深色',
    themeBinder: '皮革手帳',
    themeJournal: '復古日記',
    themeGlass: '玻璃',
    themeRoyal: '皇家典雅',
    themeGreenble: 'Greenble',
    categoryName: '分類名稱',
    categoryColor: '顏色',
    categoryIcon: '圖示',
    create: '建立',
    login: '登入',
    logout: '登出',
    share: '分享',
    shareToGlobal: '分享至全球提示詞',
    shareDescription: '將您的提示詞分享給社群。發布前您可以再次編輯。',
    anonymous: '匿名分享',
    tags: '標籤',
    tagsPlaceholder: '例如：風景, 科幻, 寫實 (以逗號分隔)',
    uploadImage: '上傳參考圖片',
    publish: '發布至全球',
    comments: '評論',
    writeComment: '寫下評論...',
    noComments: '尚未有評論。搶先頭香！',
    loginToComment: '登入以評分和評論',
    rating: '評分',
    image: '圖片',
    source: '來源',
    originalSourceUrl: '原文出處連結',
    termsOfService: '服務條款',
    privacyPolicy: '隱私權聲明',
    webViewWarningTitle: '請在瀏覽器中開啟',
    webViewWarningMessage: '您正在使用 {app}。為了獲得最佳體驗並使用 Google 登入，請在瀏覽器中開啟此網站。',
    webViewWarningMessageGeneric: '您正在使用應用程式內建瀏覽器。為了獲得最佳體驗並使用 Google 登入，請在瀏覽器中開啟此網站。',
    webViewWarningInstructions: '複製上方網址並貼到 Safari、Chrome 或您偏好的瀏覽器中。',
    webViewWarningClose: '我知道了',
    tourNext: '下一步',
    tourStart: '開始體驗',
    tourStep1Title: '本地圖書館',
    tourStep1Content: '這是您的個人提示詞收藏庫，隨時隨地都可存取，甚至離線也能使用！',
    tourStep2Title: '建立新提示詞',
    tourStep2Content: '點擊這裡新增提示詞。內建 AI 助手可協助您優化內容。',
    tourStep3Title: '分類管理',
    tourStep3Content: '在這裡管理您的分類。自訂顏色與圖示，依照您的喜好整理提示詞。',
    tourStep4Title: '分享至全球',
    tourStep4Content: '將您最棒的提示詞分享給社群！點擊卡片上的分享圖示即可發布。',
    tourStep5Title: '分享升級！',
    tourStep5Content: '分享 5 篇提示詞即可解鎖創作者徽章！持續分享可獲得銀幣、星星和金幣徽章。',
    tourComplete: '完成教學',
    selectAll: '全選',
    deselectAll: '取消全選',
    deleteSelected: '刪除已選',

    changeAvatar: '更換頭像',
    chooseAvatarTitle: '選擇頭像',
    levelLabel: '等級',
    select: '選擇',
    locked: '未解鎖',
    upload: '上傳',
    uploading: '上傳中...',
    avatarUploadHint: '星級創作者之後可上傳自訂頭像。',
    avatarUploadNotUnlocked: '等級未解鎖自訂上傳功能。',
    avatarUploadNotConfigured: '尚未設定 Cloudinary。',
    avatarUploadFailed: '上傳失敗。',

    upgradeGuide: '升級說明',
    upgradeGuideTitle: '升級說明',
  },
  ja: {
    appTitle: 'PromptsGo',
    searchPlaceholder: 'プロンプトを検索...',
    newPrompt: '新規プロンプト',
    categories: 'カテゴリー',
    allPrompts: 'すべてのプロンプト',
    globalPrompts: 'グローバル',
    myLibrary: 'ライブラリ',
    localPrompts: 'ローカルプロンプト',
    uncategorized: '未分類',
    edit: '編集',
    delete: '削除',
    copy: 'コピー',
    copied: 'コピーしました！',
    save: '保存',
    cancel: 'キャンセル',
    title: 'タイトル',
    description: '説明',
    positivePrompt: 'ポジティブ',
    negativePrompt: 'ネガティブ',
    note: 'メモ',
    notePlaceholder: '個人的なメモ、モデル設定、ヒントを追加...',
    selectCategories: 'カテゴリーを選択',
    noPrompts: 'プロンプトが見つかりません。作成しましょう！',
    refineWithAI: 'AIで改善',
    refining: '改善中...',
    confirmDelete: '本当に削除しますか？',
    manageCategories: '管理',
    addCategory: 'カテゴリー追加',
    settings: '設定',
    language: '言語',
    theme: 'テーマ',
    themeLight: 'ライト',
    themeDark: 'ダーク',
    themeBinder: 'バインダー',
    themeJournal: 'ジャーナル',
    themeGlass: 'グラス',
    themeRoyal: 'ロイヤル',
    themeGreenble: 'Greenble',
    categoryName: 'カテゴリー名',
    categoryColor: '色',
    categoryIcon: 'アイコン',
    create: '作成',
    login: 'ログイン',
    logout: 'ログアウト',
    share: '共有',
    shareToGlobal: 'グローバルに共有',
    shareDescription: 'コミュニティと共有します。公開前に編集できます。',
    anonymous: '匿名で共有',
    tags: 'タグ',
    tagsPlaceholder: '例: 風景, SF, リアル (カンマ区切り)',
    uploadImage: '参考画像をアップロード',
    publish: 'グローバルに公開',
    comments: 'コメント',
    writeComment: 'コメントを書く...',
    noComments: 'コメントはまだありません。',
    loginToComment: 'ログインして評価・コメント',
    rating: '評価',
    image: '画像',
    source: 'ソース',
    originalSourceUrl: '元のソースURL',
    termsOfService: '利用規約',
    privacyPolicy: 'プライバシーポリシー',
    webViewWarningTitle: 'ブラウザで開く',
    webViewWarningMessage: '{app}を使用しています。最高の体験とGoogleログインを使用するには、ブラウザでこのウェブサイトを開いてください。',
    webViewWarningMessageGeneric: 'アプリ内ブラウザを使用しています。最高の体験とGoogleログインを使用するには、ブラウザでこのウェブサイトを開いてください。',
    webViewWarningInstructions: '上記のURLをコピーして、Safari、Chrome、またはお好みのブラウザに貼り付けてください。',
    webViewWarningClose: '了解',
    tourNext: '次へ',
    tourStart: '開始',
    tourStep1Title: 'ローカルライブラリ',
    tourStep1Content: '個人のプロンプトはここに保存されます。いつでも、オフラインでもアクセスできます！',
    tourStep2Title: '新規作成',
    tourStep2Content: 'ここをクリックして新しいプロンプトを作成します。AIアシスタントが内容の改善をお手伝いします。',
    tourStep3Title: 'カテゴリー',
    tourStep3Content: 'ここでカテゴリーを管理します。色やアイコンをカスタマイズして、自分好みに整理しましょう。',
    tourStep4Title: 'グローバルに共有',
    tourStep4Content: '最高のプロンプトをコミュニティと共有しましょう！カードの共有アイコンをクリックして公開します。',
    tourStep5Title: '共有でレベルアップ！',
    tourStep5Content: '5つのプロンプトを共有してクリエイターバッジを解除！シルバー、スター、ゴールドバッジを獲得しよう。',
    tourComplete: 'ツアー完了',
    selectAll: 'すべて選択',
    deselectAll: 'すべて選択解除',
    deleteSelected: '選択したものを削除',

    changeAvatar: 'アバター変更',
    chooseAvatarTitle: 'アバター選択',
    levelLabel: 'レベル',
    select: '選択',
    locked: '未解放',
    upload: 'アップロード',
    uploading: 'アップロード中...',
    avatarUploadHint: 'スタークリエイター以降はカスタムアバターをアップロードできます。',
    avatarUploadNotUnlocked: 'このレベルではアップロードできません。',
    avatarUploadNotConfigured: 'Cloudinary が設定されていません。',
    avatarUploadFailed: 'アップロードに失敗しました。',

    upgradeGuide: 'アップグレードガイド',
    upgradeGuideTitle: 'アップグレードガイド',
  },
  ko: {
    appTitle: 'PromptsGo',
    searchPlaceholder: '프롬프트 검색...',
    newPrompt: '새 프롬프트',
    categories: '카테고리',
    allPrompts: '전체 프롬프트',
    globalPrompts: '글로벌 프롬프트',
    myLibrary: '내 라이브러리',
    localPrompts: '로컬 프롬프트',
    uncategorized: '미분류',
    edit: '편집',
    delete: '삭제',
    copy: '복사',
    copied: '복사됨!',
    save: '저장',
    cancel: '취소',
    title: '제목',
    description: '설명',
    positivePrompt: '긍정 프롬프트',
    negativePrompt: '부정 프롬프트',
    note: '노트',
    notePlaceholder: '개인 메모, 모델 설정, 팁을 추가하세요...',
    selectCategories: '카테고리 선택',
    noPrompts: '프롬프트가 없습니다. 새로 만들어보세요!',
    refineWithAI: 'AI로 다듬기',
    refining: '다듬는 중...',
    confirmDelete: '정말 삭제하시겠습니까?',
    manageCategories: '관리',
    addCategory: '카테고리 추가',
    settings: '설정',
    language: '언어',
    theme: '테마',
    themeLight: '라이트',
    themeDark: '다크',
    themeBinder: '바인더',
    themeJournal: '저널',
    themeGlass: '글래스',
    themeRoyal: '로열',
    themeGreenble: 'Greenble',
    categoryName: '카테고리 이름',
    categoryColor: '색상',
    categoryIcon: '아이콘',
    create: '생성',
    login: '로그인',
    logout: '로그아웃',
    share: '공유',
    shareToGlobal: '글로벌 프롬프트에 공유',
    shareDescription: '커뮤니티에 공유합니다. 게시 전 내용을 수정할 수 있어요.',
    anonymous: '익명으로 공유',
    tags: '태그',
    tagsPlaceholder: '예: 풍경, SF, 리얼(쉼표로 구분)',
    uploadImage: '참고 이미지 업로드',
    publish: '글로벌에 게시',
    comments: '댓글',
    writeComment: '댓글 작성...',
    noComments: '아직 댓글이 없습니다. 첫 댓글을 남겨보세요!',
    loginToComment: '로그인하여 평가 및 댓글 작성',
    rating: '평점',
    image: '이미지',
    source: '출처',
    originalSourceUrl: '원본 출처 URL',
    termsOfService: '서비스 약관',
    privacyPolicy: '개인정보 처리방침',
    webViewWarningTitle: '브라우저에서 열기',
    webViewWarningMessage: '{app}을(를) 사용 중입니다. 최적의 경험과 Google 로그인을 위해 브라우저에서 열어주세요.',
    webViewWarningMessageGeneric: '인앱 브라우저를 사용 중입니다. 최적의 경험과 Google 로그인을 위해 브라우저에서 열어주세요.',
    webViewWarningInstructions: '위 URL을 복사해 Safari/Chrome 등 브라우저에 붙여넣어 주세요.',
    webViewWarningClose: '확인',
    tourNext: '다음',
    tourStart: '시작',
    tourStep1Title: '로컬 라이브러리',
    tourStep1Content: '개인 프롬프트가 저장되는 곳입니다. 오프라인에서도 접근할 수 있어요!',
    tourStep2Title: '새로 만들기',
    tourStep2Content: '여기에서 새 프롬프트를 만들 수 있습니다. AI 도움으로 더 좋게 다듬을 수 있어요.',
    tourStep3Title: '카테고리',
    tourStep3Content: '여기서 카테고리를 관리하세요. 색과 아이콘을 커스터마이즈해 정리할 수 있어요.',
    tourStep4Title: '글로벌에 공유',
    tourStep4Content: '최고의 프롬프트를 커뮤니티에 공유하세요! 공유 아이콘을 눌러 게시할 수 있어요.',
    tourStep5Title: '공유로 레벨업!',
    tourStep5Content: '프롬프트 5개를 공유하면 크리에이터 배지를 잠금 해제합니다! 계속 공유해 실버/스타/골드 배지를 획득하세요.',
    tourComplete: '투어 완료',
    selectAll: '전체 선택',
    deselectAll: '선택 해제',
    deleteSelected: '선택 삭제',

    changeAvatar: '아바타 변경',
    chooseAvatarTitle: '아바타 선택',
    levelLabel: '레벨',
    select: '선택',
    locked: '잠김',
    upload: '업로드',
    uploading: '업로드 중...',
    avatarUploadHint: '스타 창작자 이후에는 커스텀 아바타를 업로드할 수 있어요.',
    avatarUploadNotUnlocked: '이 레벨에서는 업로드할 수 없습니다.',
    avatarUploadNotConfigured: 'Cloudinary가 설정되지 않았습니다.',
    avatarUploadFailed: '업로드에 실패했습니다.',

    upgradeGuide: '업그레이드 안내',
    upgradeGuideTitle: '업그레이드 안내',
  },
};
