-- This SQL file is optional - it demonstrates how to add sample global prompts with the new models
-- You can run this in Supabase SQL Editor if you want to add example prompts

-- Example: Insert a sample global prompt with Veo 3.1 model tag
-- INSERT INTO global_prompts (
--   id, title, description, positive, negative, note,
--   author_id, author_name, author_avatar,
--   tags, model_tags, image,
--   rating, rating_count, views,
--   created_at, updated_at
-- ) VALUES (
--   'example-veo-3.1',
--   'Veo 3.1 Video Generation',
--   'Create stunning videos with Veo 3.1',
--   'A beautiful cinematic video of a sunset over mountains',
--   'low quality, blurry',
--   'Use high quality settings',
--   NULL,
--   'Example User',
--   NULL,
--   ARRAY['video', 'cinematic'],
--   ARRAY['Veo 3.1'],
--   NULL,
--   5.0, 1, 0,
--   NOW(), NOW()
-- );

-- The new models are now available in MODELS.MD:
-- - Veo 3.1
-- - Sora 2 Pro
-- - Kling 2.6
-- - Luma Ray3
-- - Wan 2.5
-- - Hailuo 2.3
-- - LTX-2 Pro
-- - Seedance Pro

-- These models will automatically appear in:
-- 1. ShareModal when creating/editing global prompts
-- 2. GlobalView model filter dropdown
-- 3. PromptModal when editing local prompts

